language: r
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/inst/examples/_bookdown_files

env:
  global:
    - PATH=$HOME/bin:$PATH
    - secure: "SqzxApnemGsS6eJeg72b+ca6CCoXAwTPu2vD5ypjKqFbwDL9QEOs8SnewT4GV7b3JUjSeBsR1vQ3nZIle91UX8koFtn2xWWiFJLHQ20oP8ZDkg7mCYLtlhQN87tcTMx2pG9dzA/H467mt1ghO/HgebS2BfGgfizvB1TEk3AoWWHEwlh/eKxNeYrSzHi7wGlJs3bGWZancuTv6itzpjl02gwshE4U04rGlNciG1yIr8eSZMPit7Q8P7tlDU/t0gjXH2ZT0uejF/3U7G/ywQxJ68HWt0aWL/2umIEDGSp3GfoM+HOMOhO7cAKFyYAsggW9TFSEBMcaZVmONvWyZbcaWJTRos5T7gmHpd8tBPq0B8fpWN50aNj9c9+uVAPljqMs84l/0eb9qJMuzwvl7fN3d/8rZhvekCh7z2sY9fMww2ekKrnpJ7y9yZvfNxaYWMOQJzp6WNBW4xjoDzubAzSctVRZnOmiUzQu9Fpmtitb87FzRjO6OKNtyuutthr/59OFtxO/ElfwT499e/6QyVt6hoFMX3u4dXV1kPpdtx8jnleK7UqBakRLM8dVj9wehLqRJnn3/MYLJc2cRd5n4XMPToHGheH9ongV7/9sy9hWukF6h47IP/z4eUP6k0ZADHxt2Ivmid9Eb5ECx/9giwib1tI94ESBWXLosVud1GoncfQ="

before_install:
  - git config --global user.email "cpsievert1@gmail.com"
  - git config --global user.name "cpsievert"
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"

before_script:
  - "[ -x \"$HOME/bin/phantomjs\" ] || Rscript -e \"webshot::install_phantomjs()\""

script:
  - make
  - ls _book

after_success:
  - ./deploy_github
