# Testing HTML widgets from R

The current trend in testing HTML widget R packages is to verify that certain R commands construct an expected data structure. However, since this data structure has to be converted to JSON, and input into a JavaScript function(s), this approach doesn't guarantee that the end result is correct. Some HTML widgets use JavaScript libraries with their own testing framework, but if those tests change, R package authors may be oblivious to errors when upgrading to a new version. A proper testing framework for this type of software should be able to programmatically ensure that R commands create the correct web content, which involves constructing, parsing, and possibly manipulating the Document Object Model (DOM).

HTML widgets that don't change based on user events will only have to construct and parse the DOM, so an R package like __rdom__ would be suitable for implementing tests. HTML widgets that do change based on user events will need to program these events using something like __RSelenium__.  I know first-hand from work on __animint__ that integrating __RSelenium__ with a unit testing framework such as __testthat__ is not trivial, so the community could benefit from a detailed explanation of the approach.