---
title: "Untitled"
author: "Carson Sievert"
date: "February 3, 2015"
output: html_document
---

### Tidbits from [@viewing-pipeline].

> Two strong reasons why motion graphics is superior to static plots for many cognitive tasks:
    * Smooth transistions between images allow us to recognize objects as the same across changing views, i.e., objects retain their identity in our perception (see also object constancy -- http://bost.ocks.org/mike/constancy/); whereas exposure to disconnected, still images present the task of identifying objects across pictures.
    * The speed of moving points can convey information in addition to location
    
> As real-time manipulation of plots becomes more widespread, the sophication of users has to grow, as well as the awareness of new possibilities on the side of the implementers.


### Tidbits from [@Wilkinson:2005].

#### Definitions


#### Nice quotes

> "People in business and science have more trouble communicating than discovering" Preface. Page x.

> "This book focuses on rules for constructing graphs mathematically and then representing them as graphics aesthetically". (pg. 1)



### Tidbits from [@Wilhelm:2005].

> "To guide novices through the possibilities of interactive data analysis it is helpful to automatically run through a set of possible and interesting selections." (pg. 535)